@startuml
skinparam classAttributeIconSize 0
class Car {
    -private
    #protected
    ~package private
    +public
    {static} String id
    void see()
    {abstract} void  move()
}

class aoDi {

}
class baoMa {

}
interface A<T>{
 -- this--
 ==
 ..
 __
 __ this __
 .. this ..
  +getName()
}
note left of A:这是一个备注
note bottom of A : 底部备注
note top of A : 顶部备注
note right of A : 底部备注
note "the case 是咧" as N1
Car..N1
N1 .. A
Driver - Car : drivers >
Car *- Wheel : have 4 >
Car -- Persion : < owns
A <|.. Car
Car "1 " *--> "many" foo1  :组合
Car "1" o--> "1 " foo2 :聚合
B <|-- B1 : 继承
A <|.. B : 实现
A1 --|> A2
C -- D
@enduml